package com.onetrust.otpublishers.headless.UI.UIProperty;

/* loaded from: t.class */
public final class t {
    public String C;
    public String I;
    public String J;
    public String K;
    public boolean L;
    public String a;
    public String b;
    public String c;
    public String d;
    public String e;
    public boolean f;
    public String g;
    public String h;
    public boolean i;
    public boolean j = true;
    public b0 k = new b0();
    public b0 l = new b0();
    public b0 m = new b0();
    public b0 n = new b0();
    public b0 o = new b0();
    public b0 p = new b0();
    public b0 q = new b0();
    public b0 r = new b0();
    public b0 s = new b0();
    public b0 t = new b0();
    public b0 u = new b0();
    public b0 v = new b0();
    public c w = new c();
    public c x = new c();
    public c y = new c();
    public d z = new d();
    public l A = new l();
    public final m B = new m();
    public k D = new k();
    public k E = new k();
    public k F = new k();
    public final i G = new i();
    public final boolean H = true;

    public final String toString() {
        StringBuilder sb = new StringBuilder("OTPCUIProperty{backgroundColor='");
        sb.append(this.a);
        sb.append("', lineBreakColor='");
        sb.append(this.b);
        sb.append("', toggleThumbColorOn='");
        sb.append(this.c);
        sb.append("', toggleThumbColorOff='");
        sb.append(this.d);
        sb.append("', toggleTrackColor='");
        sb.append(this.e);
        sb.append("', showLogoOnPC=");
        sb.append(this.f);
        sb.append(", showOTLogo=");
        sb.append(this.i);
        sb.append(", lineBreakShow='null', savePreferencesUnderline='null', pageHeaderTitle='null', rightChevronColor='");
        sb.append(this.g);
        sb.append("', summaryTitleTextProperty=");
        StringBuilder a = j.a(this.u, j.a(this.t, j.a(this.s, j.a(this.r, j.a(this.n, j.a(this.m, j.a(this.l, j.a(this.k, sb, ", summaryTitleDescriptionTextProperty="), ", dsIdTitleTextProperty="), ", dsIdTextProperty="), ", dsIdDescriptionTextProperty="), ", purposeTitleTextProperty="), ", purposeItemTextProperty="), ", alwaysActiveTextProperty="), ", acceptAllButtonProperty=");
        a.append(this.w.toString());
        a.append(", rejectAllButtonProperty=");
        a.append(this.x.toString());
        a.append(", confirmMyChoiceProperty=");
        a.append(this.y.toString());
        a.append(", closeButtonProperty=");
        a.append(this.z.toString());
        a.append(", logoProperty=");
        a.append(this.A.toString());
        a.append(", menuProperty=");
        a.append(this.B.toString());
        a.append(", backButtonColor='");
        a.append(this.C);
        a.append("', policyLinkProperty=");
        a.append(this.D.toString());
        a.append(", vendorSdkTitleTextProperty=");
        StringBuilder a2 = j.a(this.v, a, ", vendorListLinkProperty=");
        a2.append(this.E.toString());
        a2.append(", sdkListLinkProperty=");
        a2.append(this.F.toString());
        a2.append(", applyUIProperty=");
        a2.append(this.H);
        a2.append(", dsIdShow='");
        a2.append(this.I);
        a2.append("', dsIdDescriptionShow='");
        a2.append(this.J);
        a2.append("', dsIdShowDividerBar=");
        a2.append(this.L);
        a2.append('}');
        return a2.toString();
    }
}
